### ISSUE TITLE
Can you help me please!

### ISSUE THREAD

**Issue by NeoGeoFreak2004** [alex-free/video2dreamcastdisc#2]
Hey, so anyways i was trying to run the converted dreamcast video disc on my actual dreamcast and via emulation, but when i try to run it. it gives me a black screen idk how to fix this, so can you help me please.

**Comment by alex-free** [comment]
> 

Can you send over the entire output of the program, describe the original video file, maybe upload the  converted file for me to look at?

**Comment by NeoGeoFreak2004** [comment]
okay here is the converted .cdi file and the video file i converted via the program. [](url)
[Vampire Hunter Intro.zip](https://github.com/alex-free/video2dreamcastdisc/files/11415055/Vampire.Hunter.Intro.zip)

**Comment by alex-free** [comment]
> okay here is the converted .cdi file and the video file i converted via the program. [Vampire Hunter Intro.zip](https://github.com/alex-free/video2dreamcastdisc/files/11415055/Vampire.Hunter.Intro.zip)

Can you send the entire output of the video2dreamcastdisc program?

Also, do other files work for you besides this one?

**Comment by NeoGeoFreak2004** [comment]
Here Is The Output:ffmpeg version 2022-02-10-git-b6bb6b9f22-essentials_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.0 (Rev7, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      57. 21.100 / 57. 21.100
  libavcodec     59. 20.100 / 59. 20.100
  libavformat    59. 17.101 / 59. 17.101
  libavdevice    59.  5.100 / 59.  5.100
  libavfilter     8. 26.101 /  8. 26.101
  libswscale      6.  5.100 /  6.  5.100
  libswresample   4.  4.100 /  4.  4.100
  libpostproc    56.  4.100 / 56.  4.100
Input #0, mpeg, from 'C:\Users\thepl\Videos\Vampire Hunter Intro.mpeg1':
  Duration: 00:00:36.79, start: -50.106133, bitrate: 3879 kb/s
  Stream #0:0[0x1e0]: Video: mpeg1video, yuv420p(tv), 352x240 [SAR 32:27 DAR 704:405], 3600 kb/s, 25 fps, 25 tbr, 90k tbn
  Stream #0:1[0x1c0]: Audio: mp2, 44100 Hz, stereo, s16p, 384 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg1video (native) -> mpeg1video (native))
Press [q] to stop, [?] for help
[mpeg1video @ 000001faf359da40] too many threads/slices (16), reducing to 15
[mpeg1video @ 000001faf35a6940] [Eval @ 00000030891fda40] Undefined constant or missing '(' in 'Lowerk'
[mpeg1video @ 000001faf35a6940] Unable to parse option value "Lowerk"
[mpeg1video @ 000001faf35a6940] Error setting option maxrate to value Lowerk.
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
ffmpeg version 2022-02-10-git-b6bb6b9f22-essentials_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.0 (Rev7, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      57. 21.100 / 57. 21.100
  libavcodec     59. 20.100 / 59. 20.100
  libavformat    59. 17.101 / 59. 17.101
  libavdevice    59.  5.100 / 59.  5.100
  libavfilter     8. 26.101 /  8. 26.101
  libswscale      6.  5.100 /  6.  5.100
  libswresample   4.  4.100 /  4.  4.100
  libpostproc    56.  4.100 / 56.  4.100
Input #0, mpeg, from 'C:\Users\thepl\Videos\Vampire Hunter Intro.mpeg1':
  Duration: 00:00:36.79, start: -50.106133, bitrate: 3879 kb/s
  Stream #0:0[0x1e0]: Video: mpeg1video, yuv420p(tv), 352x240 [SAR 32:27 DAR 704:405], 3600 kb/s, 25 fps, 25 tbr, 90k tbn
  Stream #0:1[0x1c0]: Audio: mp2, 44100 Hz, stereo, s16p, 384 kb/s
Stream mapping:
  Stream #0:1 -> #0:0 (mp2 (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to 'audio.wav':
  Metadata:
    ISFT            : Lavf59.17.101
  Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, stereo, s16, 1411 kb/s
    Metadata:
      encoder         : Lavc59.20.100 pcm_s16le
size=    6309kB time=00:00:36.72 bitrate=1407.2kbits/s speed= 399x
video:0kB audio:6309kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.001207%
||||||||||||   ADX Audio decompression tool Ver.4.70    ||||||||||
Software Audio Encoder for "CRI ADX for Dreamcast"     1999-11-30
Copyright(c) 1996-1999 CRI

Input sound data file: 'audio.wav'
ADX Compressed data file : 'audio.adx'
Sampling frequency : 44100 Hz = Input sound data
No. of channels   : 2
Input audio sample   : 1615104 smpl = 36.0 sec <44100 Hz>
ADX output sample    : 1615104 smpl(Blk:1615104 smpl) = 36.0 sec <44100 Hz>
....................
LegalADX v1.0 By Alex Free (C)2022

Converting...

Done! The output file audio.sfa is compatible with sfdmuxapp.exe/sfdmux.dll/Dreamcast Movie Creator.
||||||||||  CRI SFDMUX 1.07 ||||||||||
Sofdec Multiplexer 1999-05-20
Copyright (c) 1998,1999 CRI

-V=video.m1v
   Error [-213] Cannot find MPEG1/Video header.
Error [-320] Illegal option.
The system cannot find the file specified.
mkisofs: Warning: -rock has same effect as -rational-rock on this platform.
Total translation table size: 0
Total rockridge attributes bytes: 975
Total directory bytes: 2954
Path table size(bytes): 24
621 extents written (1 MB)
CDI4DC - 0.3b - (C)reated by [big_fury]SiZiOUS
Also other files that i made prior to this happing, it still went to a black screen.

**Comment by alex-free** [comment]
FFMPEG can't convert that kind of file, it says that in the output so it won't work for that file. That doesn't appear to be standard MPEG-1, what is it the native PSX video format for MDEC?

**Comment by NeoGeoFreak2004** [comment]
i tried to use a mp4 file with this program and it still didn't work. also im on windows 11 BTW.

**Comment by alex-free** [comment]
> i tried to use a mp4 file and an AVI file with this program and it still didn't work. also im on windows 11 BTW.

Can you send me the full output for the MP4?

**Comment by NeoGeoFreak2004** [comment]
Sure Here is the Output for the mp4:
ffmpeg version 2022-02-10-git-b6bb6b9f22-essentials_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.0 (Rev7, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      57. 21.100 / 57. 21.100
  libavcodec     59. 20.100 / 59. 20.100
  libavformat    59. 17.101 / 59. 17.101
  libavdevice    59.  5.100 / 59.  5.100
  libavfilter     8. 26.101 /  8. 26.101
  libswscale      6.  5.100 /  6.  5.100
  libswresample   4.  4.100 /  4.  4.100
  libpostproc    56.  4.100 / 56.  4.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 000002268a41b3c0] st: 1 edit list: 1 Missing key frame while searching for timestamp: 0
[mov,mp4,m4a,3gp,3g2,mj2 @ 000002268a41b3c0] st: 1 edit list 1 Cannot find an index entry before timestamp: 0.
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\thepl\Videos\Test4Dreamcast.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 0
    compatible_brands: mp41avc1
    creation_time   : 2023-05-07T22:35:20.000000Z
    encoder         : vlc 3.0.18 stream output
    encoder-eng     : vlc 3.0.18 stream output
  Duration: 00:02:16.12, start: 0.000000, bitrate: 3954 kb/s
  Stream #0:0[0x1](eng): Audio: mp3 (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 381 kb/s (default)
    Metadata:
      creation_time   : 2023-05-07T22:35:20.000000Z
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](eng): Video: mpeg1video (mp1v / 0x7631706D), yuv420p(tv), 352x240 [SAR 32:27 DAR 704:405], 3600 kb/s, SAR 417:352 DAR 139:80, 24.96 fps, 25 tbr, 90k tbn (default)
    Metadata:
      creation_time   : 2023-05-07T22:35:20.000000Z
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:1 -> #0:0 (mpeg1video (native) -> mpeg1video (native))
Press [q] to stop, [?] for help
[mpeg1video @ 000002268a4223c0] too many threads/slices (16), reducing to 15
[mpeg1video @ 000002268a422a40] [Eval @ 0000004c345fdad0] Undefined constant or missing '(' in 'Lowerk'
[mpeg1video @ 000002268a422a40] Unable to parse option value "Lowerk"
[mpeg1video @ 000002268a422a40] Error setting option maxrate to value Lowerk.
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
ffmpeg version 2022-02-10-git-b6bb6b9f22-essentials_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.0 (Rev7, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      57. 21.100 / 57. 21.100
  libavcodec     59. 20.100 / 59. 20.100
  libavformat    59. 17.101 / 59. 17.101
  libavdevice    59.  5.100 / 59.  5.100
  libavfilter     8. 26.101 /  8. 26.101
  libswscale      6.  5.100 /  6.  5.100
  libswresample   4.  4.100 /  4.  4.100
  libpostproc    56.  4.100 / 56.  4.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001974dcbab80] st: 1 edit list: 1 Missing key frame while searching for timestamp: 0
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001974dcbab80] st: 1 edit list 1 Cannot find an index entry before timestamp: 0.
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\thepl\Videos\Test4Dreamcast.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 0
    compatible_brands: mp41avc1
    creation_time   : 2023-05-07T22:35:20.000000Z
    encoder         : vlc 3.0.18 stream output
    encoder-eng     : vlc 3.0.18 stream output
  Duration: 00:02:16.12, start: 0.000000, bitrate: 3954 kb/s
  Stream #0:0[0x1](eng): Audio: mp3 (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 381 kb/s (default)
    Metadata:
      creation_time   : 2023-05-07T22:35:20.000000Z
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](eng): Video: mpeg1video (mp1v / 0x7631706D), yuv420p(tv), 352x240 [SAR 32:27 DAR 704:405], 3600 kb/s, SAR 417:352 DAR 139:80, 24.96 fps, 25 tbr, 90k tbn (default)
    Metadata:
      creation_time   : 2023-05-07T22:35:20.000000Z
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (mp3 (mp3float) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to 'audio.wav':
  Metadata:
    major_brand     : isom
    minor_version   : 0
    compatible_brands: mp41avc1
    ISFT            : Lavf59.17.101
  Stream #0:0(eng): Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, stereo, s16, 1411 kb/s (default)
    Metadata:
      creation_time   : 2023-05-07T22:35:20.000000Z
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc59.20.100 pcm_s16le
size=   23310kB time=00:02:16.09 bitrate=1403.1kbits/s speed= 640x
video:0kB audio:23310kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000327%
||||||||||||   ADX Audio decompression tool Ver.4.70    ||||||||||
Software Audio Encoder for "CRI ADX for Dreamcast"     1999-11-30
Copyright(c) 1996-1999 CRI

Input sound data file: 'audio.wav'
ADX Compressed data file : 'audio.adx'
Sampling frequency : 44100 Hz = Input sound data
No. of channels   : 2
Input audio sample   : 5967360 smpl = 135.0 sec <44100 Hz>
ADX output sample    : 5967360 smpl(Blk:5967360 smpl) = 135.0 sec <44100 Hz>
...................*
LegalADX v1.0 By Alex Free (C)2022

Converting...

Done! The output file audio.sfa is compatible with sfdmuxapp.exe/sfdmux.dll/Dreamcast Movie Creator.
||||||||||  CRI SFDMUX 1.07 ||||||||||
Sofdec Multiplexer 1999-05-20
Copyright (c) 1998,1999 CRI

-V=video.m1v
   Error [-213] Cannot find MPEG1/Video header.
Error [-320] Illegal option.
The system cannot find the file specified.
mkisofs: Warning: -rock has same effect as -rational-rock on this platform.
Total translation table size: 0
Total rockridge attributes bytes: 975
Total directory bytes: 2954
Path table size(bytes): 24
621 extents written (1 MB)
CDI4DC - 0.3b - (C)reated by [big_fury]SiZiOUS
http://sbibuilder.shorturl.com/

**Comment by alex-free** [comment]
Oh it has nothing to do with the file. What bitrate are you using? Can you take a screenshot or copy the output before it starts converting (the very top of the window)

**Comment by NeoGeoFreak2004** [comment]
the video bitrate is 3600 kb/s and the audio bitrate is 396 kb/s. and i am using higher settings.

**Comment by alex-free** [comment]
> the video bitrate is 3600 kb/s and the audio bitrate is 396 kb/s. and i am using the higher setting. here is the settings i used.
> 
> ![Screenshot (9)](https://user-images.githubusercontent.com/76540678/236707257-3b5227bc-fc94-49fa-a629-b81a4cdd30a0.png)
> 
> 

Lmao type 3200 instead of the actual word higher it will work

**Comment by NeoGeoFreak2004** [comment]
OMG It worked great! Thank you for all of your help!

**Comment by alex-free** [comment]
> OMG It worked great! Thank you for all of your help!

Of course! Have fun friend
